# Generated by Django 5.2.5 on 2025-08-24 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="World",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("z", models.IntegerField()),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("air", "Air"),
                            ("grass", "Grass"),
                            ("dirt", "Dirt"),
                            ("stone", "Stone"),
                            ("water", "Water"),
                            ("sand", "Sand"),
                            ("wood", "Wood"),
                        ],
                        default="air",
                        max_length=16,
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="api.world",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["world", "z", "y", "x"],
                        name="api_block_world_i_adde3c_idx",
                    )
                ],
                "unique_together": {("world", "x", "y", "z")},
            },
        ),
    ]
