# Generated by Django 5.2.5 on 2025-08-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_project_share_token_projectcollaborator"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="node_positions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
