# Generated by Django 5.2.5 on 2025-08-27 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["project", "source", "target"],
                name="graph_edge_project_712769_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["project", "path"], name="graph_file_project_e64cab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["project", "file"], name="graph_node_project_dd02f6_idx"
            ),
        ),
    ]
