# Generated by Django 5.2.5 on 2025-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0002_project_owner_edge_graph_edge_project_712769_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="edge",
            name="graph_edge_project_712769_idx",
        ),
        migrations.RemoveIndex(
            model_name="file",
            name="graph_file_project_e64cab_idx",
        ),
        migrations.RemoveIndex(
            model_name="node",
            name="graph_node_project_dd02f6_idx",
        ),
        migrations.RemoveField(
            model_name="project",
            name="owner",
        ),
        migrations.AddField(
            model_name="node",
            name="pos_x",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="node",
            name="pos_y",
            field=models.FloatField(default=0),
        ),
    ]
