services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    # no host ports exposed (backend uses Docker DNS "db")

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend.dev
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: 1
    depends_on:
      - db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -lc "python manage.py migrate &&
              daphne -b 0.0.0.0 -p 8000 config.asgi:application"


  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend.dev
    env_file: .env
    environment:
      NEXT_TELEMETRY_DISABLED: 1
      DJANGO_API_BASE: http://backend:8000
      NEXT_PUBLIC_DJANGO_WS_BASE: ws://localhost:8080
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev -- -p 3000 -H 0.0.0.0

volumes:
  db-data:
  frontend_node_modules:
