# Generated by Django 5.2.5 on 2025-08-18 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_project_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAnalysis",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("zip_file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("graph", models.JSONField(blank=True, default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
    ]
