# Generated by Django 5.2.5 on 2025-08-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_projectanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectanalysis",
            name="source",
            field=models.CharField(
                choices=[("upload", "Upload"), ("github", "GitHub")],
                default="upload",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="source_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="projectanalysis",
            name="zip_file",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/%Y/%m/%d/"
            ),
        ),
    ]
