# Generated by Django 5.0.6 on 2025-08-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="positions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
