# Generated by Django 5.0.6 on 2025-08-29 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_positions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
