# Generated by Django 5.0.6 on 2025-08-29 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_shared_with"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="editors",
            field=models.ManyToManyField(
                blank=True, related_name="editor_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
