# Generated by Django 5.0.6 on 2025-08-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_editors"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="shapes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
