# Generated by Django 5.2.5 on 2025-08-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2000, unique=True)),
                ("domain", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("text", models.TextField(blank=True, default="")),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
            ],
            options={
                "ordering": ["-fetched_at"],
            },
        ),
    ]
