# Generated by Django 5.2.5 on 2025-08-23 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darkweb", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={},
        ),
        migrations.AlterField(
            model_name="page",
            name="domain",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="sha256",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="url",
            field=models.URLField(unique=True),
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("email", "email"),
                            ("ip", "ip"),
                            ("btc", "btc"),
                            ("xmr", "xmr"),
                            ("pgp", "pgp"),
                            ("url", "url"),
                            ("domain", "domain"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("value", models.TextField(db_index=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("kind", "value")},
            },
        ),
        migrations.CreateModel(
            name="Mention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="darkweb.entity",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="darkweb.page",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["page"], name="darkweb_men_page_id_92abe2_idx"
                    ),
                    models.Index(
                        fields=["entity"], name="darkweb_men_entity__d4fe73_idx"
                    ),
                ],
                "unique_together": {("page", "entity")},
            },
        ),
    ]
