# Generated by Django 5.2.5 on 2025-08-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darkweb", "0002_alter_page_options_alter_page_domain_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("q", models.CharField(blank=True, default="", max_length=500)),
                (
                    "entity_kind",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "entity_value",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "domain_contains",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("15m", "Every 15 minutes"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                        ],
                        default="hourly",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notify_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("notify_webhook", models.URLField(blank=True, default="")),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("since", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
