# Generated by Django 5.2.5 on 2025-08-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darkweb", "0003_alert"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2000, unique=True)),
                ("domain", models.CharField(db_index=True, max_length=255)),
                ("depth", models.IntegerField(default=1)),
                ("frequency", models.CharField(default="hourly", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("last_crawled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="alert",
            name="notify_email",
            field=models.EmailField(blank=True, default="", max_length=320),
        ),
        migrations.AlterField(
            model_name="alert",
            name="notify_webhook",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
    ]
