FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY frontend/package*.json ./
RUN npm ci

COPY frontend ./
RUN npm run build && npm prune --omit=dev

EXPOSE 3000
CMD ["npm","start"]
